baseURL: https://chincoteaguepropertyowners.com/
languageCode: en-us
title: Chincoteague Property Owners
theme: PaperMod

googleAnalytics: UA-69025481-3

params:
  ShowShareButtons: true
  hideFooter: true