baseURL: https://chincoteaguepropertyowners.com/
languageCode: en-us
title: Chincoteague Property Owners
theme: PaperMod

googleAnalytics: UA-69025481-3

params:
  ShowShareButtons: true
  hideFooter: true
  hideMeta: true
  enableRobotsTXT: true
  ShowBreadCrumbs: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title:
    Content: |
      ![](/sunset.jpeg) 
      # &nbsp;
      ### The purpose of this site is to provide information about Seacrets to Island residents and other interested people.
      
